# Generated by Django 3.2 on 2021-04-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210421_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliver_by',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='mode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='deliver_by',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='mode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
