# Generated by Django 3.2 on 2021-04-23 14:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210422_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 23, 14, 53, 31, 262058, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
