# Generated by Django 3.0.14 on 2021-04-20 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('shop', '0001_initial'),
        ('feedback', '0002_feedback_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback',
            new_name='ProductFeedback',
        ),
        migrations.CreateModel(
            name='OrderFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_orders', to='order.OrderItem')),
            ],
        ),
    ]
