# Generated by Django 3.2 on 2021-04-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20210420_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfeedback',
            name='rating',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='productfeedback',
            name='rating',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
