# Generated by Django 3.2 on 2021-04-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_units',
            field=models.DecimalField(decimal_places=0, default=32, max_digits=3),
            preserve_default=False,
        ),
    ]
